name: bitcoinz-mini
version: master
summary: Portable BitcoinZ anonymous z-address generator for offline / paper wallets
description: |
  bitcoinz-mini is a minimal, portable BitcoinZ wallet generator in Go.

grade: devel
confinement: strict

apps:
  bitcoinz-mini:
    command: bitcoinz-mini

parts:
  bitcoinz-mini:
    source: .
    plugin: go
    go-importpath: github.com/bitcoinz-pod/bitcoinz-mini
